'use client'

import { createContext, useContext, useEffect, useState } from 'react'

type Language = 'ar' | 'en'

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.project': 'المشروع',
    'nav.privacy': 'الخصوصية',
    'nav.terms': 'الشروط',
    'nav.support': 'الدعم',
    'nav.getStarted': 'ابدأ الآن',
    'hero.title': 'منصة ذكية للتجارة الإلكترونية',
    'hero.subtitle': 'حل Smart White Label متكامل يربط التجار والعملاء في مكان واحد. ابدأ متجرك الإلكتروني اليوم بأدوات احترافية وسهلة الاستخدام',
    'hero.startFree': 'ابدأ مجاناً',
    'hero.watchDemo': 'شاهد العرض التوضيحي',
    'features.title': 'كل ما تحتاجه لنجاح متجرك',
    'features.subtitle': 'نوفر لك أدوات احترافية ومتكاملة لإدارة متجرك الإلكتروني بكفاءة عالية',
    'features.customStores': 'متاجر مخصصة بالكامل',
    'features.customerExperience': 'تجربة عملاء استثنائية',
    'features.advancedSecurity': 'أمان متقدم',
    'features.analytics': 'تحليلات وتقارير',
    'features.responsive': 'تطبيق متجاوب',
    'features.freeTrial': 'نسخة تجريبية مجانية',
    'pricing.title': 'اختر الخطة المناسبة لك',
    'pricing.subtitle': 'خطط مرنة تناسب جميع أحجام الأعمال من الشركات الناشئة إلى المؤسسات الكبيرة',
    'pricing.basic': 'الباقة الأساسية',
    'pricing.advanced': 'الباقة المتقدمة',
    'pricing.professional': 'الباقة الاحترافية',
    'pricing.enterprise': 'باقة الشراكات',
    'pricing.mostPopular': 'الأكثر شعبية',
    'pricing.choosePlan': 'اختر الباقة',
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.subtitle': 'تجارب حقيقية من تجار وأصحاب متاجر يستخدمون CodeBH يومياً',
    'cta.title': 'جاهز لبدء رحلتك في التجارة الإلكترونية؟',
    'cta.subtitle': 'انضم إلى آلاف التجار الناجحين الذين يثقون في CodeBH لإدارة متاجرهم',
    'cta.startNow': 'ابدأ مجاناً الآن',
    'footer.description': 'منصة مبتكرة للتجارة الإلكترونية تربط بين التجار والعملاء بسهولة وأمان، مع توفير أدوات احترافية لإدارة المتاجر الإلكترونية بكفاءة عالية.',
    'footer.platform': 'المنصة',
    'footer.support': 'الدعم',
    'footer.contact': 'تواصل معنا',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.madeWith': 'صُنع بـ',
    'footer.inBahrain': 'في البحرين',
    'common.learnMore': 'اعرف المزيد',
    'common.tryNow': 'جرّب الآن',
    'common.activeNow': 'نشط الآن',
    'common.trustedBy': 'موثوق به من قبل آلاف التجار والعملاء',
    'common.rating': 'تقييم 4.9/5',
    'common.sslSecurity': 'أمان SSL متقدم',
    'common.highPerformance': 'أداء فائق السرعة',
    
    // Project Page Translations
    'project.storeName': 'متجرك',
    'project.subtitle': 'منصة التجارة الإلكترونية الذكية',
    'project.tagline': 'حل متكامل لتمكين التجار من إطلاق متاجرهم الإلكترونية بكفاءة وسرعة',
    'project.presentationDate': 'عرض تقديمي للمستثمرين - 2025',
    'project.executiveSummary': 'الملخص التنفيذي',
    'project.executiveSummaryContent': 'متجرك هو منصة تجارة إلكترونية مبتكرة من نوع SaaS (Software as a Service) تعتمد على نموذج Smart White Label، تمكن التجار من إطلاق متاجرهم الإلكترونية الخاصة دون الحاجة لتطوير تطبيقات منفصلة.',
    'project.executiveSummaryContent2': 'تتميز المنصة بكونها Multi-tenant حيث يمكن لتطبيق واحد خدمة عدة متاجر من خلال نظام رموز المتاجر الفريدة (Store Codes)، مما يوفر حلاً اقتصادياً وفعالاً للتجار الصغار والمتوسطين.',
    'project.investmentOpportunity': 'الفرصة الاستثمارية',
    'project.investmentOpportunityContent': 'سوق التجارة الإلكترونية في نمو مستمر مع إمكانيات هائلة للنمو والربحية. منصة CodeBH تقدم حلول مبتكرة لسد فجوة في السوق.',
    'project.systemMechanics': 'كيف يعمل النظام؟',
    'project.systemMechanicsContent': 'نظام متكامل يربط التجار والعملاء في مكان واحد مع إدارة شاملة للمنتجات والطلبات والمدفوعات.',
    'project.completedFeatures': 'المميزات المكتملة',
    'project.completedFeaturesContent': 'تطبيق متكامل مع جميع الوظائف الأساسية للتجارة الإلكترونية، واجهة مستخدم حديثة، ونظام دفع آمن.',
    'project.marketProblem': 'المشكلة في السوق',
    'project.ourSolution': 'الحل الذي نقدمه',
    'project.problem1': 'تكلفة عالية: تطوير تطبيق تجارة إلكترونية مخصص يكلف من 10,000$ إلى 50,000$',
    'project.problem2': 'وقت طويل: التطوير يستغرق من 3 إلى 6 أشهر',
    'project.problem3': 'صيانة مكلفة: التحديثات والصيانة تتطلب فريق تقني دائم',
    'project.problem4': 'نقص الخبرة: معظم التجار ليس لديهم خبرة تقنية كافية',
    'project.solution1': 'إطلاق سريع',
    'project.solution1Desc': 'يمكن للتاجر البدء في غضون 24 ساعة فقط',
    'project.solution2': 'تكلفة منخفضة',
    'project.solution2Desc': 'اشتراك شهري يبدأ من 50$ فقط',
    'project.solution3': 'تخصيص كامل',
    'project.solution3Desc': 'ألوان، شعار، منتجات، وطرق دفع خاصة',
    'project.solution4': 'تحديثات تلقائية',
    'project.solution4Desc': 'جميع التحسينات والمميزات الجديدة مجاناً',
    'project.forInvestor': 'للمستثمر (صاحب المنصة)',
    'project.forMerchant': 'للتاجر',
    'project.investorPoint1': 'ينشر تطبيقاً واحداً على App Store و Google Play',
    'project.investorPoint2': 'يدير جميع التجار من لوحة تحكم مركزية (Super Admin)',
    'project.investorPoint3': 'يحصل على اشتراكات شهرية من كل تاجر',
    'project.investorPoint4': 'يقدم الدعم الفني والتحديثات المستمرة',
    'project.merchantPoint1': 'يسجل في المنصة ويحصل على رمز متجر فريد (Store Code)',
    'project.merchantPoint2': 'يحصل على لوحة تحكم ويب لإدارة متجره بالكامل',
    'project.merchantPoint3': 'يخصص الثيم، الشعار، المنتجات، طرق الدفع، والأسعار',
    'project.merchantPoint4': 'يحصل على QR Code لمشاركته مع عملائه',
    'project.frontend': 'Frontend',
    'project.backend': 'Backend',
    'project.payment': 'Payment',
    'project.infrastructure': 'Infrastructure',
    'project.techStack': 'التقنيات المستخدمة',
    'project.revenueModel': 'نموذج الإيرادات',
    'project.basicPlan': 'الباقة الأساسية',
    'project.advancedPlan': 'الباقة المتقدمة',
    'project.professionalPlan': 'الباقة الاحترافية',
    'project.enterprisePlan': 'باقة الشراكات',
    'project.100Products': '100 منتج',
    'project.5Employees': '5 موظفين',
    'project.1GBStorage': '1GB تخزين',
    'project.500Products': '500 منتج',
    'project.15Employees': '15 موظف',
    'project.5GBStorage': '5GB تخزين',
    'project.unlimitedProducts': 'منتجات غير محدودة',
    'project.50Employees': '50 موظف',
    'project.20GBStorage': '20GB تخزين',
    'project.everythingUnlimited': 'كل شيء غير محدود',
    'project.unlimitedUsers': 'مستخدمين غير محدودين',
    'project.unlimitedStorage': 'تخزين غير محدود',
    'project.targetMarket': 'السوق المستهدف',
    'project.smallMerchants': 'التجار الصغار',
    'project.smallMerchantsDesc': 'أصحاب الأعمال الصغيرة والمتوسطة',
    'project.startups': 'الشركات الناشئة',
    'project.startupsDesc': 'الشركات الجديدة في مجال التجارة الإلكترونية',
    'project.enterprises': 'المؤسسات الكبيرة',
    'project.enterprisesDesc': 'الشركات الكبيرة التي تحتاج حلول مخصصة',
    'project.competitiveAdvantages': 'المزايا التنافسية',
    'project.advantage1': 'حل Smart White Label متكامل',
    'project.advantage2': 'واجهة مستخدم حديثة وسهلة',
    'project.advantage3': 'دعم فني 24/7',
    'project.advantage4': 'أسعار تنافسية',
    'project.advantage5': 'أمان متقدم',
    'project.advantage6': 'قابلية التوسع',
    'project.financialNeeds': 'الاحتياجات المالية',
    'project.development': 'التطوير',
    'project.developmentDesc': 'تطوير المميزات الجديدة وتحسين الأداء',
    'project.marketing': 'التسويق',
    'project.marketingDesc': 'حملات تسويقية وزيادة الوعي بالعلامة التجارية',
    'project.operations': 'العمليات',
    'project.operationsDesc': 'البنية التحتية والدعم الفني',
    'project.risks': 'المخاطر والتحديات',
    'project.risk1': 'المنافسة',
    'project.mitigation1': 'التركيز على الابتكار والجودة',
    'project.risk2': 'التغييرات التقنية',
    'project.mitigation2': 'الاستثمار في البحث والتطوير',
    'project.risk3': 'التحديات الاقتصادية',
    'project.mitigation3': 'تنويع مصادر الدخل',
    'project.productionReady': 'جاهز للإنتاج',
    'project.platforms': 'منصات (iOS, Android, Web)',
    'project.features': 'ميزة متكاملة',
    'project.stores': 'متاجر يمكن استضافتها',
    'project.ctaTitle': 'هل تريد الاستثمار في المستقبل؟',
    'project.ctaSubtitle': 'انضم إلينا في رحلة بناء منصة التجارة الإلكترونية الرائدة في المنطقة',
    'project.contactInvestors': 'تواصل مع المستثمرين',
    'project.tryDemo': 'جرب النسخة التجريبية',
    
    // Home Page Additional Translations
    'features.customStoresDesc': 'أنشئ متجرك الإلكتروني بتصميم احترافي وخيارات تخصيص كاملة تناسب علامتك التجارية',
    'features.customerExperienceDesc': 'واجهة سهلة وسلسة تمنح عملائك تجربة تسوق ممتعة وآمنة عبر تطبيق واحد',
    'features.advancedSecurityDesc': 'حماية قوية لبيانات التجار والعملاء مع تشفير SSL وأعلى معايير الأمان',
    'features.analyticsDesc': 'لوحة تحكم شاملة مع تقارير تفصيلية لمساعدتك على فهم أدائك واتخاذ قرارات ذكية',
    'features.responsiveDesc': 'تطبيق سريع يعمل على جميع الأجهزة والشاشات بسلاسة تامة وأداء عالي',
    'features.freeTrialDesc': 'جرّب المنصة مجاناً عبر النسخة التجريبية على الويب واكتشف جميع المميزات',
    
    // Pricing Translations
    'pricing.basicDesc': 'مثالية للمتاجر الصغيرة والمبتدئين',
    'pricing.advancedDesc': 'للأعمال المتنامية والمتاجر النشطة',
    'pricing.professionalDesc': 'للمتاجر الكبيرة والاحترافية',
    'pricing.enterpriseDesc': 'حلول شاملة للشراكات التجارية',
    'pricing.period': 'BHD/30 يوم',
    'pricing.100Products': '100 منتج',
    'pricing.5Employees': '5 موظفين',
    'pricing.1GBStorage': '1GB تخزين',
    'pricing.emailSupport': 'دعم عبر البريد الإلكتروني',
    'pricing.500Products': '500 منتج',
    'pricing.15Employees': '15 موظف',
    'pricing.5GBStorage': '5GB تخزين',
    'pricing.prioritySupport': 'دعم أولوي',
    'pricing.advancedReports': 'تقارير متقدمة',
    'pricing.unlimitedProducts': 'منتجات غير محدودة',
    'pricing.50Employees': '50 موظف',
    'pricing.20GBStorage': '20GB تخزين',
    'pricing.managerSupport': 'دعم عبر مدير اساعة',
    'pricing.customAPI': 'API مخصص',
    'pricing.everythingUnlimited': 'كل شيء غير محدود',
    'pricing.unlimitedUsers': 'مستخدمين غير محدودين',
    'pricing.unlimitedStorage': 'تخزين غير محدود',
    'pricing.dedicatedManager': 'مدير حساب مخصص',
    'pricing.customSupport': 'دعم مخصص 24/7',
    'pricing.fullCustomization': 'تخصيص كامل',
    'pricing.guaranteedSLA': 'SLA مضمون',
    
    // Testimonials
    'testimonials.customer1Name': 'أحمد المنصور',
    'testimonials.customer1Role': 'صاحب متجر إلكتروني',
    'testimonials.customer1Content': 'منصة CodeBH غيرت طريقة إدارتي لمتجري بالكامل! سهلة الاستخدام واحترافية جداً. الدعم الفني ممتاز والتقارير التفصيلية ساعدتني على فهم عملائي بشكل أفضل.',
    'testimonials.customer2Name': 'سارة أحمد',
    'testimonials.customer2Role': 'عميلة نشطة',
    'testimonials.customer2Content': 'أستطيع التسوق من عدة متاجر في تطبيق واحد فقط! تجربة رائعة ومريحة جداً. التطبيق سريع وسهل ويوفر لي الكثير من الوقت.',
    'testimonials.customer3Name': 'محمد العلي',
    'testimonials.customer3Role': 'رائد أعمال',
    'testimonials.customer3Content': 'الدعم الفني استثنائي والمنصة توفر كل الأدوات التي أحتاجها لإدارة متجري بكفاءة عالية. استطعت زيادة مبيعاتي بنسبة 200% خلال 3 أشهر فقط!',
    
    // Trust Section
    'trust.title': 'موثوق به من قبل آلاف التجار والعملاء',
    'trust.rating': 'تقييم 4.9/5',
    'trust.sslSecurity': 'أمان SSL متقدم',
    'trust.highPerformance': 'أداء فائق السرعة',
    
    // CTA Section
    
    // Footer Translations
    'footer.platform': 'المنصة',
    'footer.support': 'الدعم',
    'footer.legal': 'القانونية',
    'footer.features': 'المميزات',
    'footer.pricing': 'الأسعار',
    'footer.demo': 'النسخة التجريبية',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.community': 'المجتمع',
    'footer.usagePolicy': 'سياسة الاستخدام',
    'footer.cookiePolicy': 'سياسة ملفات تعريف الارتباط',
    'footer.description': 'منصة CodeBH هي الحل الأمثل للتجار الذين يريدون إنشاء متاجر إلكترونية احترافية بسهولة وسرعة. نوفر جميع الأدوات والخدمات التي تحتاجها لنجاح متجرك.',
    'footer.address': 'البحرين - المنامة',
    'footer.allRightsReserved': 'جميع الحقوق محفوظة',
    'footer.madeWith': 'صُنع بـ',
    'footer.inBahrain': 'في البحرين',
    
    // Support Page Translations
    'support.title': 'مركز الدعم والمساعدة',
    'support.subtitle': 'نحن هنا لمساعدتك في كل خطوة. ابحث عن إجابات لأسئلتك أو تواصل مع فريق الدعم لدينا.',
    'support.stats.24_7': 'دعم مستمر',
    'support.stats.response': 'دقيقة استجابة',
    'support.stats.satisfaction': 'نسبة رضا العملاء',
    'support.stats.solved': 'مشكلة تم حلها',
    'support.contactMethods.email': 'البريد الإلكتروني',
    'support.contactMethods.emailDesc': 'للاستفسارات العامة والدعم',
    'support.contactMethods.merchants': 'دعم التجار',
    'support.contactMethods.merchantsDesc': 'للتجار وأصحاب المتاجر',
    'support.contactMethods.bugs': 'الأخطاء التقنية',
    'support.contactMethods.bugsDesc': 'للإبلاغ عن الأخطاء والمشاكل',
    'support.contactMethods.suggestions': 'الاقتراحات',
    'support.contactMethods.suggestionsDesc': 'شاركنا أفكارك لتطوير المنصة',
    'support.workingHours.general': 'الدعم العام',
    'support.workingHours.generalHours': 'الأحد - الخميس\n9:00 ص - 9:00 م',
    'support.workingHours.generalStatus': 'مفتوح الآن',
    'support.workingHours.merchants': 'دعم التجار',
    'support.workingHours.merchantsHours': 'السبت - الخميس\n8:00 ص - 10:00 م',
    'support.workingHours.merchantsStatus': 'متاح',
    'support.workingHours.emergency': 'الطوارئ التقنية',
    'support.workingHours.emergencyHours': '24/7\nعلى مدار الساعة',
    'support.workingHours.emergencyStatus': 'دائماً متاح',
    'support.workingHours.friday': 'الجمعة',
    'support.workingHours.fridayHours': '2:00 م - 9:00 م\nدعم محدود',
    'support.workingHours.fridayStatus': 'متاح جزئياً',
    'support.faq.title': 'الأسئلة الشائعة',
    'support.faq.subtitle': 'إجابات على أكثر الأسئلة شيوعاً',
    'support.faq.q1': 'كيف يمكنني الاشتراك كتاجر؟',
    'support.faq.a1': 'للاشتراك كتاجر، اتبع الخطوات التالية: حمل التطبيق وأنشئ حساباً جديداً، اختر "تاجر" عند التسجيل، املأ نموذج طلب الاشتراك مع المعلومات المطلوبة، اختر الباقة المناسبة، أرسل الطلب وانتظر الموافقة (1-3 أيام)، بعد الموافقة، ستتم مراسلتك لإتمام الدفع، سيتم تفعيل متجرك خلال 24 ساعة من الدفع.',
    'support.faq.q2': 'هل يمكنني إضافة بوابة دفع خاصة بي؟',
    'support.faq.a2': 'نعم، يمكنك إضافة بوابات دفع خارجية لمتجرك. الطرق المدعومة حالياً: PayTabs، Stripe، وبوابات أخرى. يجب أن تمتلك حساباً نشطاً في بوابة الدفع أولاً. نحن نوفر الربط التقني فقط.',
    'support.faq.q3': 'ماذا يحدث عند انتهاء الاشتراك؟',
    'support.faq.a3': 'عند انتهاء فترة الاشتراك: ستصلك تذكيرات قبل 15، 7، و 3 أيام من الانتهاء، فترة سماح 7 أيام إضافية لتجديد الاشتراك، المتجر سيتوقف عن العمل مؤقتاً، بياناتك محفوظة لمدة 30 يوماً، يمكن إعادة تفعيل المتجر بتجديد الاشتراك.',
    'support.faq.q4': 'هل التطبيق آمن للاستخدام؟',
    'support.faq.a4': 'نعم، نحن نلتزم بأعلى معايير الأمان: التشفير بمعايير SSL/TLS، عدم حفظ معلومات البطاقات في خوادمنا، خوادم محمية بأحدث تقنيات الأمان، فحص دوري للأمان من خبراء متخصصين، الالتزام بقوانين حماية البيانات الدولية، تحديثات أمنية منتظمة.',
    'support.tabs.general': 'الدعم العام',
    'support.tabs.merchants': 'دعم التجار',
    'support.tabs.customers': 'دعم العملاء',
    'support.tabs.technical': 'الدعم التقني',
    'support.contact.title': 'تواصل معنا',
    'support.contact.subtitle': 'اختر الطريقة المناسبة لك للتواصل مع فريق الدعم',
    
    // Terms Page Translations
    'terms.title': 'شروط الاستخدام',
    'terms.subtitle': 'يرجى قراءة هذه الشروط والأحكام بعناية قبل استخدام منصة CodeBH',
    'terms.lastUpdated': 'آخر تحديث: يناير 2025',
    'terms.sections.definitions': 'التعريفات والمصطلحات',
    'terms.sections.definitionsDesc': 'تعريف المصطلحات المستخدمة في هذه الشروط والأحكام لضمان الوضوح والفهم الصحيح.',
    'terms.sections.acceptance': 'قبول الشروط',
    'terms.sections.acceptanceDesc': 'شروط الموافقة على استخدام المنصة والالتزام بالأحكام المذكورة.',
    'terms.sections.merchants': 'شروط التجار',
    'terms.sections.merchantsDesc': 'الالتزامات والحقوق الخاصة بالتجار المسجلين في المنصة.',
    'terms.sections.customers': 'شروط العملاء',
    'terms.sections.customersDesc': 'الحقوق والالتزامات الخاصة بالعملاء المستخدمين للمنصة.',
    'terms.sections.payment': 'طرق الدفع',
    'terms.sections.paymentDesc': 'الطرق المتاحة للدفع والشروط المرتبطة بكل طريقة.',
    'terms.sections.dataProtection': 'حماية البيانات',
    'terms.sections.dataProtectionDesc': 'التزامات المنصة في حماية البيانات الشخصية والمالية للمستخدمين.',
    'terms.sections.disputes': 'حل النزاعات',
    'terms.sections.disputesDesc': 'آلية حل النزاعات والخلافات بين الأطراف المختلفة.',
    'terms.sections.liability': 'حدود المسؤولية',
    'terms.sections.liabilityDesc': 'تحديد حدود مسؤولية المنصة في مختلف الحالات والظروف.',
    'terms.merchantObligations.title': 'التزامات التجار',
    'terms.merchantObligations.item1': 'ضمان دقة جميع معلومات المنتجات والأسعار',
    'terms.merchantObligations.item2': 'ضمان جودة المنتجات وتطابقها مع الوصف',
    'terms.merchantObligations.item3': 'الرد على استفسارات العملاء خلال 24 ساعة',
    'terms.merchantObligations.item4': 'معالجة وتنفيذ الطلبات في الوقت المحدد',
    'terms.merchantObligations.item5': 'تقديم خدمة عملاء ممتازة ومهنية',
    'terms.merchantObligations.item6': 'احترام جميع القوانين المحلية والدولية',
    'terms.customerRights.title': 'حقوق العملاء',
    'terms.customerRights.item1': 'الحصول على معلومات دقيقة عن المنتجات',
    'terms.customerRights.item2': 'استلام المنتجات في الحالة والوقت المتفق عليه',
    'terms.customerRights.item3': 'الحق في الإرجاع والاستبدال حسب سياسة كل متجر',
    'terms.customerRights.item4': 'حماية البيانات الشخصية والمالية',
    'terms.customerRights.item5': 'الحصول على دعم فني عند الحاجة',
    'terms.customerRights.item6': 'تقييم المنتجات والمتاجر بشفافية',
    'terms.prohibited.title': 'الممارسات المحظورة',
    'terms.prohibited.item1': 'بيع منتجات مقلدة أو مزيفة',
    'terms.prohibited.item2': 'بيع منتجات مخدرة أو خطيرة',
    'terms.prohibited.item3': 'استخدام صور منتجات مضللة',
    'terms.prohibited.item4': 'انتهاك حقوق الملكية الفكرية',
    'terms.prohibited.item5': 'التلاعب في التقييمات أو الآراء',
    'terms.prohibited.item6': 'التمييز ضد العملاء لأي سبب كان',
    'terms.prohibited.item7': 'نشر محتوى مخالف للآداب العامة',
    'terms.prohibited.item8': 'استخدام معلومات العملاء لأغراض غير قانونية',
    'terms.paymentMethods.cod': 'الدفع عند الاستلام',
    'terms.paymentMethods.codDesc': 'الدفع نقداً عند وصول المنتج',
    'terms.paymentMethods.codAvailable': 'متاح في جميع المناطق المدعومة',
    'terms.paymentMethods.bankTransfer': 'التحويل البنكي',
    'terms.paymentMethods.bankTransferDesc': 'تحويل المبلغ إلى حساب التاجر البنكي',
    'terms.paymentMethods.bankTransferAvailable': 'مع رفع إثبات التحويل',
    'terms.paymentMethods.paytabs': 'PayTabs',
    'terms.paymentMethods.paytabsDesc': 'بوابة دفع آمنة ومعتمدة',
    'terms.paymentMethods.paytabsAvailable': 'للتجار المسجلين',
    'terms.paymentMethods.stripe': 'Stripe',
    'terms.paymentMethods.stripeDesc': 'معالجة دفع سريعة وآمنة',
    'terms.paymentMethods.stripeAvailable': 'للتجار المسجلين',
    'terms.importantNotice': 'ملاحظة مهمة',
    'terms.importantNoticeDesc': 'هذه الشروط تُطبق على جميع المستخدمين (التجار والعملاء) وتشكل اتفاقية قانونية ملزمة بينك وبين الشركة. باستخدامك لهذه المنصة، أنت توافق على الالتزام بهذه الشروط والأحكام.',
    
    // Privacy Page Translations
    'privacy.title': 'سياسة الخصوصية',
    'privacy.subtitle': 'نحن ملتزمون بحماية خصوصيتك وبياناتك الشخصية. اقرأ سياسة الخصوصية الخاصة بنا لفهم كيفية جمع واستخدام وحماية معلوماتك.',
    'privacy.lastUpdated': 'آخر تحديث: يناير 2025',
    'privacy.sections.dataCollection': 'البيانات التي نجمعها',
    'privacy.sections.dataCollectionDesc': 'نقوم بجمع البيانات الضرورية لتقديم خدماتنا بشكل فعال وآمن، بما في ذلك المعلومات الشخصية وبيانات الاستخدام.',
    'privacy.sections.dataUsage': 'كيف نستخدم بياناتك',
    'privacy.sections.dataUsageDesc': 'نستخدم بياناتك لتحسين خدماتنا وتقديم تجربة مخصصة، مع ضمان عدم مشاركتها مع أطراف ثالثة دون موافقتك.',
    'privacy.sections.dataProtection': 'حماية البيانات والأمان',
    'privacy.sections.dataProtectionDesc': 'نطبق أعلى معايير الأمان لحماية بياناتك، بما في ذلك التشفير المتقدم والمراقبة المستمرة.',
    'privacy.sections.userRights': 'حقوقك في البيانات',
    'privacy.sections.userRightsDesc': 'لديك الحق في الوصول لبياناتك وتعديلها أو حذفها في أي وقت، وفقاً للقوانين المعمول بها.',
    'privacy.dataTypes.personal': 'البيانات الشخصية الأساسية',
    'privacy.dataTypes.personalItem1': 'الاسم الكامل',
    'privacy.dataTypes.personalItem2': 'البريد الإلكتروني',
    'privacy.dataTypes.personalItem3': 'رقم الهاتف',
    'privacy.dataTypes.personalItem4': 'العنوان',
    'privacy.dataTypes.personalItem5': 'تاريخ الميلاد (اختياري)',
    'privacy.dataTypes.usage': 'بيانات الاستخدام والتفاعل',
    'privacy.dataTypes.usageItem1': 'سجل التصفح',
    'privacy.dataTypes.usageItem2': 'تفضيلات التسوق',
    'privacy.dataTypes.usageItem3': 'بيانات الطلبات',
    'privacy.dataTypes.usageItem4': 'معلومات الجهاز',
    'privacy.dataTypes.usageItem5': 'الموقع الجغرافي (بموافقتك)',
    'privacy.dataTypes.commercial': 'البيانات التجارية',
    'privacy.dataTypes.commercialItem1': 'معلومات المتجر',
    'privacy.dataTypes.commercialItem2': 'بيانات التاجر',
    'privacy.dataTypes.commercialItem3': 'المعلومات التجارية',
    'privacy.dataTypes.commercialItem4': 'البيانات المصرفية',
    'privacy.security.encryption': 'التشفير المتقدم',
    'privacy.security.encryptionDesc': 'جميع البيانات مشفرة باستخدام SSL/TLS',
    'privacy.security.servers': 'خوادم آمنة',
    'privacy.security.serversDesc': 'استضافة على خوادم محمية ومحدثة',
    'privacy.security.backups': 'نسخ احتياطية',
    'privacy.security.backupsDesc': 'نسخ احتياطية منتظمة مشفرة',
    'privacy.security.monitoring': 'رصد الأمان',
    'privacy.security.monitoringDesc': 'مراقبة 24/7 للأنشطة المشبوهة',
    'privacy.rights.access': 'حق الوصول',
    'privacy.rights.accessDesc': 'يمكنك طلب نسخة من جميع بياناتك المخزنة لدينا',
    'privacy.rights.correction': 'حق التصحيح',
    'privacy.rights.correctionDesc': 'تحديث أو تصحيح بياناتك الشخصية في أي وقت',
    'privacy.rights.deletion': 'حق الحذف',
    'privacy.rights.deletionDesc': 'طلب حذف بياناتك الشخصية من أنظمتنا',
    'privacy.rights.portability': 'حق النقل',
    'privacy.rights.portabilityDesc': 'تصدير بياناتك بصيغة قابلة للقراءة',
    'privacy.rights.restriction': 'حق التقييد',
    'privacy.rights.restrictionDesc': 'تقييد معالجة بياناتك في ظروف معينة',
    'privacy.rights.objection': 'حق الاعتراض',
    'privacy.rights.objectionDesc': 'الاعتراض على معالجة بياناتك لأغراض تسويقية',
    'privacy.cookies.title': 'ملفات تعريف الارتباط (Cookies)',
    'privacy.cookies.desc': 'نستخدم ملفات تعريف الارتباط لتحسين تجربتك على موقعنا. يمكنك التحكم في هذه الملفات من خلال إعدادات المتصفح.',
    'privacy.cookies.essential': 'ملفات أساسية',
    'privacy.cookies.essentialDesc': 'ضرورية لعمل الموقع بشكل صحيح',
    'privacy.cookies.analytics': 'ملفات تحليلية',
    'privacy.cookies.analyticsDesc': 'تساعدنا في فهم كيفية استخدام الموقع',
    'privacy.cookies.marketing': 'ملفات تسويقية',
    'privacy.cookies.marketingDesc': 'تُستخدم لعرض إعلانات مخصصة',
    'privacy.contact.title': 'تواصل معنا',
    'privacy.contact.desc': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية أو تريد ممارسة حقوقك، يرجى التواصل معنا.',
    'privacy.contact.email': 'privacy@codebh.com',
    'privacy.contact.phone': '+973 1711 1888',
    'privacy.dataTypes.title': 'أنواع البيانات التي نجمعها',
    'privacy.security.title': 'تدابير الأمان والحماية',
    'privacy.rights.title': 'حقوقك في البيانات',
    'privacy.contactSection.title': 'هل لديك استفسارات حول الخصوصية؟',
    'privacy.contactSection.desc': 'فريقنا متاح للإجابة على جميع استفساراتك حول سياسة الخصوصية',
    'privacy.contactSection.email': 'راسلنا عبر البريد الإلكتروني',
    'privacy.contactSection.phone': 'اتصل بنا',
    'privacy.intro.title': 'مرحباً بك في منصة CodeBH',
    'privacy.intro.desc1': 'نحن في CodeBH نؤمن بأن خصوصيتك وأمان بياناتك هما حقان أساسيان. هذه السياسة توضح كيفية جمع واستخدام وحماية معلوماتك الشخصية عند استخدام منصتنا الذكية للتجارة الإلكترونية من نوع Smart White Label.',
    'privacy.intro.desc2': 'منصة CodeBH هي حل تقني متكامل يمكّن التجار من إنشاء متاجرهم الإلكترونية والعملاء من التسوق بسهولة وأمان من خلال تطبيق واحد متطور.',
  },
  en: {
    'nav.home': 'Home',
    'nav.project': 'Project',
    'nav.privacy': 'Privacy',
    'nav.terms': 'Terms',
    'nav.support': 'Support',
    'nav.getStarted': 'Get Started',
    'hero.title': 'Smart E-commerce Platform',
    'hero.subtitle': 'Complete Smart White Label solution that connects merchants and customers in one place. Start your online store today with professional and easy-to-use tools',
    'hero.startFree': 'Start Free',
    'hero.watchDemo': 'Watch Demo',
    'features.title': 'Everything you need for your store success',
    'features.subtitle': 'We provide you with professional and integrated tools to manage your online store with high efficiency',
    'features.customStores': 'Fully Customized Stores',
    'features.customerExperience': 'Exceptional Customer Experience',
    'features.advancedSecurity': 'Advanced Security',
    'features.analytics': 'Analytics & Reports',
    'features.responsive': 'Responsive App',
    'features.freeTrial': 'Free Trial Version',
    'pricing.title': 'Choose the plan that suits you',
    'pricing.subtitle': 'Flexible plans that suit all business sizes from startups to large enterprises',
    'pricing.basic': 'Basic Plan',
    'pricing.advanced': 'Advanced Plan',
    'pricing.professional': 'Professional Plan',
    'pricing.enterprise': 'Enterprise Plan',
    'pricing.mostPopular': 'Most Popular',
    'pricing.choosePlan': 'Choose Plan',
    'testimonials.title': 'What our customers say',
    'testimonials.subtitle': 'Real experiences from merchants and store owners who use CodeBH daily',
    'cta.title': 'Ready to start your e-commerce journey?',
    'cta.subtitle': 'Join thousands of successful merchants who trust CodeBH to manage their stores',
    'cta.startNow': 'Start Free Now',
    'footer.description': 'Innovative e-commerce platform that connects merchants and customers easily and securely, providing professional tools for efficient online store management.',
    'footer.platform': 'Platform',
    'footer.support': 'Support',
    'footer.contact': 'Contact Us',
    'footer.rights': 'All rights reserved',
    'footer.madeWith': 'Made with',
    'footer.inBahrain': 'in Bahrain',
    'common.learnMore': 'Learn More',
    'common.tryNow': 'Try Now',
    'common.activeNow': 'Active Now',
    'common.trustedBy': 'Trusted by thousands of merchants and customers',
    'common.rating': '4.9/5 Rating',
    'common.sslSecurity': 'Advanced SSL Security',
    'common.highPerformance': 'High Performance',
    
    // Project Page Translations
    'project.storeName': 'Your Store',
    'project.subtitle': 'Smart E-commerce Platform',
    'project.tagline': 'Complete solution to enable merchants to launch their online stores efficiently and quickly',
    'project.presentationDate': 'Investor Presentation - 2025',
    'project.executiveSummary': 'Executive Summary',
    'project.executiveSummaryContent': 'Your Store is an innovative SaaS (Software as a Service) e-commerce platform based on Smart White Label model, enabling merchants to launch their own online stores without the need to develop separate applications.',
    'project.executiveSummaryContent2': 'The platform is distinguished by being Multi-tenant where one application can serve multiple stores through a unique store codes system (Store Codes), providing an economical and effective solution for small and medium merchants.',
    'project.investmentOpportunity': 'Investment Opportunity',
    'project.investmentOpportunityContent': 'The e-commerce market is in continuous growth with huge potential for growth and profitability. CodeBH platform offers innovative solutions to fill a gap in the market.',
    'project.systemMechanics': 'How does the system work?',
    'project.systemMechanicsContent': 'Integrated system that connects merchants and customers in one place with comprehensive management of products, orders and payments.',
    'project.completedFeatures': 'Completed Features',
    'project.completedFeaturesContent': 'Complete application with all basic e-commerce functions, modern user interface, and secure payment system.',
    'project.marketProblem': 'Market Problem',
    'project.ourSolution': 'Our Solution',
    'project.problem1': 'High cost: Developing a custom e-commerce app costs from $10,000 to $50,000',
    'project.problem2': 'Long time: Development takes 3 to 6 months',
    'project.problem3': 'Expensive maintenance: Updates and maintenance require a permanent technical team',
    'project.problem4': 'Lack of experience: Most merchants do not have sufficient technical expertise',
    'project.solution1': 'Quick Launch',
    'project.solution1Desc': 'Merchants can start within 24 hours only',
    'project.solution2': 'Low Cost',
    'project.solution2Desc': 'Monthly subscription starting from $50 only',
    'project.solution3': 'Full Customization',
    'project.solution3Desc': 'Colors, logo, products, and custom payment methods',
    'project.solution4': 'Automatic Updates',
    'project.solution4Desc': 'All improvements and new features for free',
    'project.forInvestor': 'For Investor (Platform Owner)',
    'project.forMerchant': 'For Merchant',
    'project.investorPoint1': 'Publishes one app on App Store and Google Play',
    'project.investorPoint2': 'Manages all merchants from central control panel (Super Admin)',
    'project.investorPoint3': 'Gets monthly subscriptions from each merchant',
    'project.investorPoint4': 'Provides technical support and continuous updates',
    'project.merchantPoint1': 'Registers on the platform and gets a unique store code (Store Code)',
    'project.merchantPoint2': 'Gets a web control panel to manage his store completely',
    'project.merchantPoint3': 'Customizes theme, logo, products, payment methods, and prices',
    'project.merchantPoint4': 'Gets QR Code to share with his customers',
    'project.frontend': 'Frontend',
    'project.backend': 'Backend',
    'project.payment': 'Payment',
    'project.infrastructure': 'Infrastructure',
    'project.techStack': 'Technologies Used',
    'project.revenueModel': 'Revenue Model',
    'project.basicPlan': 'Basic Plan',
    'project.advancedPlan': 'Advanced Plan',
    'project.professionalPlan': 'Professional Plan',
    'project.enterprisePlan': 'Enterprise Plan',
    'project.100Products': '100 Products',
    'project.5Employees': '5 Employees',
    'project.1GBStorage': '1GB Storage',
    'project.500Products': '500 Products',
    'project.15Employees': '15 Employees',
    'project.5GBStorage': '5GB Storage',
    'project.unlimitedProducts': 'Unlimited Products',
    'project.50Employees': '50 Employees',
    'project.20GBStorage': '20GB Storage',
    'project.everythingUnlimited': 'Everything Unlimited',
    'project.unlimitedUsers': 'Unlimited Users',
    'project.unlimitedStorage': 'Unlimited Storage',
    'project.targetMarket': 'Target Market',
    'project.smallMerchants': 'Small Merchants',
    'project.smallMerchantsDesc': 'Small and medium business owners',
    'project.startups': 'Startups',
    'project.startupsDesc': 'New companies in e-commerce field',
    'project.enterprises': 'Large Enterprises',
    'project.enterprisesDesc': 'Large companies that need custom solutions',
    'project.competitiveAdvantages': 'Competitive Advantages',
    'project.advantage1': 'Complete Smart White Label solution',
    'project.advantage2': 'Modern and easy user interface',
    'project.advantage3': '24/7 technical support',
    'project.advantage4': 'Competitive prices',
    'project.advantage5': 'Advanced security',
    'project.advantage6': 'Scalability',
    'project.financialNeeds': 'Financial Needs',
    'project.development': 'Development',
    'project.developmentDesc': 'Developing new features and improving performance',
    'project.marketing': 'Marketing',
    'project.marketingDesc': 'Marketing campaigns and brand awareness',
    'project.operations': 'Operations',
    'project.operationsDesc': 'Infrastructure and technical support',
    'project.risks': 'Risks and Challenges',
    'project.risk1': 'Competition',
    'project.mitigation1': 'Focus on innovation and quality',
    'project.risk2': 'Technical changes',
    'project.mitigation2': 'Investment in research and development',
    'project.risk3': 'Economic challenges',
    'project.mitigation3': 'Diversify income sources',
    'project.productionReady': 'Production Ready',
    'project.platforms': 'Platforms (iOS, Android, Web)',
    'project.features': 'Integrated Features',
    'project.stores': 'Stores Can Be Hosted',
    'project.ctaTitle': 'Want to invest in the future?',
    'project.ctaSubtitle': 'Join us in building the leading e-commerce platform in the region',
    'project.contactInvestors': 'Contact Investors',
    'project.tryDemo': 'Try Demo Version',
    
    // Home Page Additional Translations
    'features.customStoresDesc': 'Create your online store with professional design and complete customization options that suit your brand',
    'features.customerExperienceDesc': 'Easy and smooth interface that gives your customers an enjoyable and secure shopping experience through one app',
    'features.advancedSecurityDesc': 'Strong protection for merchant and customer data with SSL encryption and highest security standards',
    'features.analyticsDesc': 'Comprehensive dashboard with detailed reports to help you understand your performance and make smart decisions',
    'features.responsiveDesc': 'Fast app that works on all devices and screens with complete smoothness and high performance',
    'features.freeTrialDesc': 'Try the platform for free through the web demo version and discover all features',
    
    // Pricing Translations
    'pricing.basicDesc': 'Perfect for small stores and beginners',
    'pricing.advancedDesc': 'For growing businesses and active stores',
    'pricing.professionalDesc': 'For large and professional stores',
    'pricing.enterpriseDesc': 'Comprehensive solutions for business partnerships',
    'pricing.period': 'BHD/30 days',
    'pricing.100Products': '100 products',
    'pricing.5Employees': '5 employees',
    'pricing.1GBStorage': '1GB storage',
    'pricing.emailSupport': 'Email support',
    'pricing.500Products': '500 products',
    'pricing.15Employees': '15 employees',
    'pricing.5GBStorage': '5GB storage',
    'pricing.prioritySupport': 'Priority support',
    'pricing.advancedReports': 'Advanced reports',
    'pricing.unlimitedProducts': 'Unlimited products',
    'pricing.50Employees': '50 employees',
    'pricing.20GBStorage': '20GB storage',
    'pricing.managerSupport': 'Manager support',
    'pricing.customAPI': 'Custom API',
    'pricing.everythingUnlimited': 'Everything unlimited',
    'pricing.unlimitedUsers': 'Unlimited users',
    'pricing.unlimitedStorage': 'Unlimited storage',
    'pricing.dedicatedManager': 'Dedicated account manager',
    'pricing.customSupport': 'Custom 24/7 support',
    'pricing.fullCustomization': 'Full customization',
    'pricing.guaranteedSLA': 'Guaranteed SLA',
    
    // Testimonials
    'testimonials.customer1Name': 'Ahmed Al-Mansour',
    'testimonials.customer1Role': 'Online store owner',
    'testimonials.customer1Content': 'CodeBH platform completely changed how I manage my store! Easy to use and very professional. Technical support is excellent and detailed reports helped me understand my customers better.',
    'testimonials.customer2Name': 'Sarah Ahmed',
    'testimonials.customer2Role': 'Active customer',
    'testimonials.customer2Content': 'I can shop from multiple stores in one app only! Amazing and very comfortable experience. The app is fast and easy and saves me a lot of time.',
    'testimonials.customer3Name': 'Mohammed Al-Ali',
    'testimonials.customer3Role': 'Entrepreneur',
    'testimonials.customer3Content': 'Technical support is exceptional and the platform provides all the tools I need to manage my store with high efficiency. I was able to increase my sales by 200% in just 3 months!',
    
    // Trust Section
    'trust.title': 'Trusted by thousands of merchants and customers',
    'trust.rating': '4.9/5 Rating',
    'trust.sslSecurity': 'Advanced SSL Security',
    'trust.highPerformance': 'High Performance',
    
    // CTA Section
    
    // Footer Translations
    'footer.platform': 'Platform',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.demo': 'Demo Version',
    'footer.faq': 'FAQ',
    'footer.community': 'Community',
    'footer.usagePolicy': 'Usage Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.description': 'CodeBH platform is the perfect solution for merchants who want to create professional online stores easily and quickly. We provide all the tools and services you need for your store success.',
    'footer.address': 'Bahrain - Manama',
    'footer.allRightsReserved': 'All rights reserved',
    'footer.madeWith': 'Made with',
    'footer.inBahrain': 'in Bahrain',
    
    // Support Page Translations
    'support.title': 'Support Center',
    'support.subtitle': 'We are here to help you every step of the way. Find answers to your questions or contact our support team.',
    'support.stats.24_7': 'Continuous Support',
    'support.stats.response': 'Response Time',
    'support.stats.satisfaction': 'Customer Satisfaction',
    'support.stats.solved': 'Issues Resolved',
    'support.contactMethods.email': 'Email',
    'support.contactMethods.emailDesc': 'For general inquiries and support',
    'support.contactMethods.merchants': 'Merchant Support',
    'support.contactMethods.merchantsDesc': 'For merchants and store owners',
    'support.contactMethods.bugs': 'Technical Issues',
    'support.contactMethods.bugsDesc': 'To report bugs and problems',
    'support.contactMethods.suggestions': 'Suggestions',
    'support.contactMethods.suggestionsDesc': 'Share your ideas for platform development',
    'support.workingHours.general': 'General Support',
    'support.workingHours.generalHours': 'Sunday - Thursday\n9:00 AM - 9:00 PM',
    'support.workingHours.generalStatus': 'Open Now',
    'support.workingHours.merchants': 'Merchant Support',
    'support.workingHours.merchantsHours': 'Saturday - Thursday\n8:00 AM - 10:00 PM',
    'support.workingHours.merchantsStatus': 'Available',
    'support.workingHours.emergency': 'Technical Emergency',
    'support.workingHours.emergencyHours': '24/7\nAround the clock',
    'support.workingHours.emergencyStatus': 'Always Available',
    'support.workingHours.friday': 'Friday',
    'support.workingHours.fridayHours': '2:00 PM - 9:00 PM\nLimited Support',
    'support.workingHours.fridayStatus': 'Partially Available',
    'support.faq.title': 'Frequently Asked Questions',
    'support.faq.subtitle': 'Answers to the most common questions',
    'support.faq.q1': 'How can I subscribe as a merchant?',
    'support.faq.a1': 'To subscribe as a merchant, follow these steps: Download the app and create a new account, choose "Merchant" when registering, fill out the subscription request form with required information, choose the appropriate package, send the request and wait for approval (1-3 days), after approval, you will be contacted to complete payment, your store will be activated within 24 hours of payment.',
    'support.faq.q2': 'Can I add my own payment gateway?',
    'support.faq.a2': 'Yes, you can add external payment gateways to your store. Currently supported methods: PayTabs, Stripe, and other gateways. You must have an active account with the payment gateway first. We only provide technical integration.',
    'support.faq.q3': 'What happens when the subscription expires?',
    'support.faq.a3': 'When the subscription period expires: You will receive reminders 15, 7, and 3 days before expiration, a 7-day grace period to renew the subscription, the store will temporarily stop working, your data is preserved for 30 days, the store can be reactivated by renewing the subscription.',
    'support.faq.q4': 'Is the app safe to use?',
    'support.faq.a4': 'Yes, we adhere to the highest security standards: SSL/TLS encryption, no card information stored on our servers, servers protected with latest security technologies, regular security audits by specialized experts, compliance with international data protection laws, regular security updates.',
    'support.tabs.general': 'General Support',
    'support.tabs.merchants': 'Merchant Support',
    'support.tabs.customers': 'Customer Support',
    'support.tabs.technical': 'Technical Support',
    'support.contact.title': 'Contact Us',
    'support.contact.subtitle': 'Choose the appropriate method to contact our support team',
    
    // Terms Page Translations
    'terms.title': 'Terms of Use',
    'terms.subtitle': 'Please read these terms and conditions carefully before using the CodeBH platform',
    'terms.lastUpdated': 'Last updated: January 2025',
    'terms.sections.definitions': 'Definitions and Terms',
    'terms.sections.definitionsDesc': 'Definition of terms used in these terms and conditions to ensure clarity and proper understanding.',
    'terms.sections.acceptance': 'Acceptance of Terms',
    'terms.sections.acceptanceDesc': 'Terms of agreement to use the platform and commitment to the mentioned provisions.',
    'terms.sections.merchants': 'Merchant Terms',
    'terms.sections.merchantsDesc': 'Obligations and rights specific to merchants registered on the platform.',
    'terms.sections.customers': 'Customer Terms',
    'terms.sections.customersDesc': 'Rights and obligations specific to customers using the platform.',
    'terms.sections.payment': 'Payment Methods',
    'terms.sections.paymentDesc': 'Available payment methods and conditions associated with each method.',
    'terms.sections.dataProtection': 'Data Protection',
    'terms.sections.dataProtectionDesc': 'Platform obligations in protecting users\' personal and financial data.',
    'terms.sections.disputes': 'Dispute Resolution',
    'terms.sections.disputesDesc': 'Mechanism for resolving disputes and conflicts between different parties.',
    'terms.sections.liability': 'Liability Limits',
    'terms.sections.liabilityDesc': 'Determining the limits of platform responsibility in various cases and circumstances.',
    'terms.merchantObligations.title': 'Merchant Obligations',
    'terms.merchantObligations.item1': 'Ensure accuracy of all product information and prices',
    'terms.merchantObligations.item2': 'Ensure product quality and match with description',
    'terms.merchantObligations.item3': 'Respond to customer inquiries within 24 hours',
    'terms.merchantObligations.item4': 'Process and fulfill orders on time',
    'terms.merchantObligations.item5': 'Provide excellent and professional customer service',
    'terms.merchantObligations.item6': 'Respect all local and international laws',
    'terms.customerRights.title': 'Customer Rights',
    'terms.customerRights.item1': 'Get accurate information about products',
    'terms.customerRights.item2': 'Receive products in the agreed condition and time',
    'terms.customerRights.item3': 'Right to return and exchange according to each store\'s policy',
    'terms.customerRights.item4': 'Protection of personal and financial data',
    'terms.customerRights.item5': 'Get technical support when needed',
    'terms.customerRights.item6': 'Rate products and stores transparently',
    'terms.prohibited.title': 'Prohibited Practices',
    'terms.prohibited.item1': 'Selling counterfeit or fake products',
    'terms.prohibited.item2': 'Selling drugs or dangerous products',
    'terms.prohibited.item3': 'Using misleading product images',
    'terms.prohibited.item4': 'Violating intellectual property rights',
    'terms.prohibited.item5': 'Manipulating ratings or reviews',
    'terms.prohibited.item6': 'Discriminating against customers for any reason',
    'terms.prohibited.item7': 'Publishing content contrary to public morals',
    'terms.prohibited.item8': 'Using customer information for illegal purposes',
    'terms.paymentMethods.cod': 'Cash on Delivery',
    'terms.paymentMethods.codDesc': 'Pay in cash when the product arrives',
    'terms.paymentMethods.codAvailable': 'Available in all supported areas',
    'terms.paymentMethods.bankTransfer': 'Bank Transfer',
    'terms.paymentMethods.bankTransferDesc': 'Transfer the amount to the merchant\'s bank account',
    'terms.paymentMethods.bankTransferAvailable': 'With proof of transfer upload',
    'terms.paymentMethods.paytabs': 'PayTabs',
    'terms.paymentMethods.paytabsDesc': 'Secure and certified payment gateway',
    'terms.paymentMethods.paytabsAvailable': 'For registered merchants',
    'terms.paymentMethods.stripe': 'Stripe',
    'terms.paymentMethods.stripeDesc': 'Fast and secure payment processing',
    'terms.paymentMethods.stripeAvailable': 'For registered merchants',
    'terms.importantNotice': 'Important Notice',
    'terms.importantNoticeDesc': 'These terms apply to all users (merchants and customers) and constitute a legally binding agreement between you and the company. By using this platform, you agree to comply with these terms and conditions.',
    
    // Privacy Page Translations
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'We are committed to protecting your privacy and personal data. Read our privacy policy to understand how we collect, use, and protect your information.',
    'privacy.lastUpdated': 'Last updated: January 2025',
    'privacy.sections.dataCollection': 'Data We Collect',
    'privacy.sections.dataCollectionDesc': 'We collect necessary data to provide our services effectively and securely, including personal information and usage data.',
    'privacy.sections.dataUsage': 'How We Use Your Data',
    'privacy.sections.dataUsageDesc': 'We use your data to improve our services and provide a personalized experience, ensuring it is not shared with third parties without your consent.',
    'privacy.sections.dataProtection': 'Data Protection and Security',
    'privacy.sections.dataProtectionDesc': 'We apply the highest security standards to protect your data, including advanced encryption and continuous monitoring.',
    'privacy.sections.userRights': 'Your Data Rights',
    'privacy.sections.userRightsDesc': 'You have the right to access, modify, or delete your data at any time, in accordance with applicable laws.',
    'privacy.dataTypes.personal': 'Basic Personal Data',
    'privacy.dataTypes.personalItem1': 'Full Name',
    'privacy.dataTypes.personalItem2': 'Email Address',
    'privacy.dataTypes.personalItem3': 'Phone Number',
    'privacy.dataTypes.personalItem4': 'Address',
    'privacy.dataTypes.personalItem5': 'Date of Birth (Optional)',
    'privacy.dataTypes.usage': 'Usage and Interaction Data',
    'privacy.dataTypes.usageItem1': 'Browsing History',
    'privacy.dataTypes.usageItem2': 'Shopping Preferences',
    'privacy.dataTypes.usageItem3': 'Order Data',
    'privacy.dataTypes.usageItem4': 'Device Information',
    'privacy.dataTypes.usageItem5': 'Geographic Location (with your consent)',
    'privacy.dataTypes.commercial': 'Commercial Data',
    'privacy.dataTypes.commercialItem1': 'Store Information',
    'privacy.dataTypes.commercialItem2': 'Merchant Data',
    'privacy.dataTypes.commercialItem3': 'Business Information',
    'privacy.dataTypes.commercialItem4': 'Banking Data',
    'privacy.security.encryption': 'Advanced Encryption',
    'privacy.security.encryptionDesc': 'All data is encrypted using SSL/TLS',
    'privacy.security.servers': 'Secure Servers',
    'privacy.security.serversDesc': 'Hosting on protected and updated servers',
    'privacy.security.backups': 'Backups',
    'privacy.security.backupsDesc': 'Regular encrypted backups',
    'privacy.security.monitoring': 'Security Monitoring',
    'privacy.security.monitoringDesc': '24/7 monitoring for suspicious activities',
    'privacy.rights.access': 'Right to Access',
    'privacy.rights.accessDesc': 'You can request a copy of all your data stored with us',
    'privacy.rights.correction': 'Right to Correction',
    'privacy.rights.correctionDesc': 'Update or correct your personal data at any time',
    'privacy.rights.deletion': 'Right to Deletion',
    'privacy.rights.deletionDesc': 'Request deletion of your personal data from our systems',
    'privacy.rights.portability': 'Right to Portability',
    'privacy.rights.portabilityDesc': 'Export your data in a readable format',
    'privacy.rights.restriction': 'Right to Restriction',
    'privacy.rights.restrictionDesc': 'Restrict processing of your data under certain circumstances',
    'privacy.rights.objection': 'Right to Objection',
    'privacy.rights.objectionDesc': 'Object to processing your data for marketing purposes',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.desc': 'We use cookies to improve your experience on our site. You can control these files through your browser settings.',
    'privacy.cookies.essential': 'Essential Cookies',
    'privacy.cookies.essentialDesc': 'Necessary for the website to function properly',
    'privacy.cookies.analytics': 'Analytics Cookies',
    'privacy.cookies.analyticsDesc': 'Help us understand how the site is used',
    'privacy.cookies.marketing': 'Marketing Cookies',
    'privacy.cookies.marketingDesc': 'Used to display personalized ads',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.desc': 'If you have any questions about the privacy policy or want to exercise your rights, please contact us.',
    'privacy.contact.email': 'privacy@codebh.com',
    'privacy.contact.phone': '+973 1711 1888',
    'privacy.dataTypes.title': 'Types of Data We Collect',
    'privacy.security.title': 'Security and Protection Measures',
    'privacy.rights.title': 'Your Data Rights',
    'privacy.contactSection.title': 'Do you have privacy questions?',
    'privacy.contactSection.desc': 'Our team is available to answer all your questions about the privacy policy',
    'privacy.contactSection.email': 'Email us',
    'privacy.contactSection.phone': 'Call us',
    'privacy.intro.title': 'Welcome to CodeBH Platform',
    'privacy.intro.desc1': 'At CodeBH, we believe that your privacy and data security are fundamental rights. This policy explains how we collect, use, and protect your personal information when using our smart Smart White Label e-commerce platform.',
    'privacy.intro.desc2': 'CodeBH platform is a comprehensive technical solution that enables merchants to create their online stores and customers to shop easily and securely through one advanced application.',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage) {
      setLanguage(savedLanguage)
    } else {
      const browserLang = navigator.language.split('-')[0]
      setLanguage(browserLang === 'ar' ? 'ar' : 'en')
    }
  }, [])

  useEffect(() => {
    if (mounted) {
      localStorage.setItem('language', language)
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = language
    }
  }, [language, mounted])

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar')
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}